// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKAcGD3Z7uaT18-huNQCrU6uPM-AXHhFU',
    appId: '1:479429424696:web:f8e90f46a658f795d658cd',
    messagingSenderId: '479429424696',
    projectId: 'auth-ef349',
    authDomain: 'auth-ef349.firebaseapp.com',
    storageBucket: 'auth-ef349.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCzZzO0ojgeLBDOaupEzCyfqUKQS08H74',
    appId: '1:479429424696:android:eeb7018037fc3a84d658cd',
    messagingSenderId: '479429424696',
    projectId: 'auth-ef349',
    storageBucket: 'auth-ef349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFWnV4_51APD3hTHo2tzvACSIeuTkwCIE',
    appId: '1:479429424696:ios:8a0fdebd089cdeb5d658cd',
    messagingSenderId: '479429424696',
    projectId: 'auth-ef349',
    storageBucket: 'auth-ef349.appspot.com',
    iosClientId: '479429424696-57vvtqlopsbr78vvifpp42tpt7kot1oe.apps.googleusercontent.com',
    iosBundleId: 'com.example.dropease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFWnV4_51APD3hTHo2tzvACSIeuTkwCIE',
    appId: '1:479429424696:ios:8a0fdebd089cdeb5d658cd',
    messagingSenderId: '479429424696',
    projectId: 'auth-ef349',
    storageBucket: 'auth-ef349.appspot.com',
    iosClientId: '479429424696-57vvtqlopsbr78vvifpp42tpt7kot1oe.apps.googleusercontent.com',
    iosBundleId: 'com.example.dropease',
  );
}
